name: Build and Deploy Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip update files
        run: zip -r mirobots-update-1.0.2.zip ./update-files

      - name: Upload to Netlify
        uses: netlify/actions-cli@v1
        with:
          args: deploy --dir=./ --prod
