name: Build and Deploy Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip update files
        run: zip -r mirobots-update-1.0.2.zip ./update-files

      - name: Deploy to Netlify
        uses: netlify/actions@v1
        with:
          args: deploy --dir=./ --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
